---
kind: Secret
apiVersion: v1
metadata:
  name: gitea-admin-password
  namespace: gitea-operator
data:
  password: cmVkaGF0MDA=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: gitea-user-password
  namespace: gitea-operator
data:
  password: cmVkaGF0MDA=
type: Opaque
---
kind: Gitea
apiVersion: pfe.rhpds.com/v1
metadata:
  name: repository
  namespace: gitea-operator
spec:
  giteaSsl: true
  giteaVolumeSize: 4Gi
  postgresqlVolumeSize: 4Gi
  sourceNamespace: gitea-operator
  giteaAdminUser: opentlc-mgr
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaAdminPasswordSecretName: gitea-admin-password
  giteaCreateUsers: true
  giteaGenerateUserFormat: "student%d"
  giteaUserNumber: 10
  giteaUserPasswordSecretName: gitea-user-password

  # giteaMigrateRepositories: true
  # giteaRepositoriesList:
  # - repo: https://github.com/repository1.git
  #   name: repository1
  #   private: false
  # - repo: https://github.com/repository2.git
  #   name: another-repository
  #   private: true

